name: Repository Manager
on:
  workflow_dispatch:
  schedule:
    - cron: 0 11 * 1-2,11-12 1
    - cron: 0 10 * 3-10 1
  create:
  issues:
    types: [opened, reopened, closed]
  pull_request:
    branches: [main]
    types: [opened, reopened, closed]
  issue_comment:
    types: [created]
  release:
    types: [published]

jobs:
  manager:
    name: Repository Manager
    uses: Katsute/Workflows/.github/workflows/manager.yml@main
    if: >-
      ${{
      (github.repository_owner == 'Katsute' || github.repository_owner == 'KatsuteDev' || github.repository_owner == 'KatsuteTF') &&
      github.actor != 'mashiro-san' &&
      !endsWith(github.actor, '[bot]')
      }}
    secrets:
      token: ${{ secrets.BOT }}